version: '3'
services:
  jobworker-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./certs:/app/certs
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    environment:
      - SERVER_CERT=/app/certs/server.crt
      - SERVER_KEY=/app/certs/server.key
      - CA_CERT=/app/certs/ca.crt
    privileged: true
    extra_hosts:
      - "host.docker.internal:host-gateway"